baseURL = 'https://mayrf.github.io/'
languageCode = 'en-us'
title = 'mayrf'
theme = "shibui"
name = "oida"

[params]
  # author = "mayrf"
  email = "your.email@example.com"

[author]
  name = "mayrf"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[module]
  [module.hugoVersion]
    extended = false
    min = '0.93.0'


[markup]
  [markup.highlight]
    noClasses = false
    style = "plaintext"  # effectively no colors
